import type { NextPage } from "next";
import { DarkModeContext } from "../DarkModeContext";
import Head from "next/head";
import Card from "../components/Card";
import { useContext } from "react";

const Home: NextPage = () => {
  const [darkMode, setDarkMode] = useContext(DarkModeContext);

  return (
    <div>
      <Head>
        <title>Frontend Mentor Challenge - Country APIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;600;800&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div
        className={`${
          darkMode ? "bg-very-dark-blue-bg" : "bg-very-light-gray"
        }`}
      >
        <div className="py-5 flex flex-row flex-wrap justify-center align-items gap-10">
          <Card></Card>
          <Card></Card>
          <Card></Card>
          <Card></Card>
          <Card></Card>
          <Card></Card>
          <Card></Card>
          <Card></Card>
        </div>
      </div>
    </div>
  );
};

export default Home;
